data:extend({
    {
        type = "double-setting",
        name = "crafting-speed-changer-handcrafting",
        setting_type = "startup",
        default_value = 20,
        minimum_value = 0.0000001,
        maximum_value = 100000000,
        localised_name = "Handcrafting time multiplier",
        localised_description = "Setting this to 2 will double handcrafting time. Setting to 0.5 will halve handcrafting time.",
    },
    {
        type = "double-setting",
        name = "crafting-speed-changer-assembler",
        setting_type = "startup",
        default_value = 20,
        minimum_value = 0.0000001,
        maximum_value = 100000000,
        localised_name = "Assembler time multiplier",
        localised_description = "Setting this to 2 will double assembler time. Setting to 0.5 will halve assembler time.",
    },
    {
        type = "double-setting",
        name = "crafting-speed-changer-furnace",
        setting_type = "startup",
        default_value = 3,
        minimum_value = 0.0000001,
        maximum_value = 100000000,
        localised_name = "Furnace time multiplier",
        localised_description = "Setting this to 2 will double smelting time. Setting to 0.5 will halve smelting time.",
    },
    {
        type = "double-setting",
        name = "crafting-speed-changer-lab",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 0.0000001,
        maximum_value = 100000000,
        localised_name = "Lab time multiplier",
        localised_description = "Setting this to 2 will double time taken by a lab to process science packs. Setting to 0.5 will halve the time.",
    },
})
